[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    autocmd Vimenter * execute 'NERDTree'
    map <C-t> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
    colorscheme hybrid
'''

[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
hook_add = '''
   if executable('ag')
      let g:ctrlp_use_caching=0
      let g:ctrlp_user_command='ag %s -i --nocolor --nogroup -g ""'
    endif
    let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
'''

[[plugins]]
repo = "neovimhaskell/haskell-vim"
hook_add = '''
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords
'''

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
source ~/.config/nvim/plugins/rust.rc.vim
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
source ~/.config/nvim/plugins/cow.rc.vim
'''


[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
source ~/.config/nvim/plugins/denite.rc.vim
'''


[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
